backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: text },
                  { label: Image, name: image, widget: image },
                  {
                    label: Actions,
                    name: actions,
                    widget: list,
                    field:
                      {
                        label: Link,
                        name: link,
                        widget: link,
                        collections:
                          [
                            {
                              name: "pages",
                              searchFields: ["label"],
                              displayField: "label",
                              valueField: "slug",
                            },
                          ],
                      },
                  },
                ],
            }
