backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/assets
public_folder: /assets
collections:
  - name: "template_pages"
    label: "Templated Pages"
    files:
      - file: "src/content/template_pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Hero,
              name: hero,
              widget: list,
              required: false,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                  {
                    label: Actions,
                    name: actions,
                    widget: list,
                    field:
                      {
                        label: Link,
                        name: link,
                        widget: link,
                        required: false,
                        collections:
                          [
                            {
                              name: "template_pages",
                              searchFields: ["title"],
                              displayField: "title",
                              valueField: "slug",
                            },
                            {
                              name: "pages",
                              searchFields: ["title"],
                              displayField: "title",
                              valueField: "slug",
                            },
                          ],
                      },
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              required: false,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              required: false,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: text },
                  { label: Image, name: image, widget: image },
                  {
                    label: Actions,
                    name: actions,
                    widget: list,
                    field:
                      {
                        label: Link,
                        name: link,
                        widget: link,
                        required: false,
                        collections:
                          [
                            {
                              name: "template_pages",
                              searchFields: ["title"],
                              displayField: "title",
                              valueField: "slug",
                            },
                            {
                              name: "pages",
                              searchFields: ["title"],
                              displayField: "title",
                              valueField: "slug",
                            },
                          ],
                      },
                  },
                ],
            }
      - file: "src/content/template_pages/testimonials.md"
        label: "Testimonials Page"
        name: "testimonials"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "testimonials-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - { label: Content, name: content, widget: markdown, required: false }
          - {
              label: Hero Image,
              name: heroimage,
              widget: image,
              required: false,
            }
  - name: "testimonials"
    label: "Testimonials"
    create: true
    folder: "src/content/testimonials"
    identifier_field: name
    fields:
      [
        { label: "Text", name: "text", widget: "text" },
        { label: "Name", name: "name", widget: "string" },
      ]
  - name: "homepage_testimonials"
    label: "Highlight Testimonials"
    create: true
    folder: "src/content/homepage_testimonials"
    identifier_field: name
    fields:
      [
        { label: "Text", name: "text", widget: "text" },
        { label: "Name", name: "name", widget: "string" },
      ]
  - name: "pages"
    label: "Pages"
    create: true
    folder: "src/content/pages"
    identifier_field: title
    fields:
      [
        { label: Title, name: title, widget: string },
        {
          label: Description,
          name: description,
          widget: text,
          required: false,
        },
        { label: Content, name: content, widget: markdown },
        { label: Hero Image, name: heroimage, widget: image, required: false },
        { label: Image, name: image, widget: image, required: false },
      ]
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/content/settings/menu.md"
        label: "Navigation Menu"
        name: "menu"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "menu",
            }
          - label: "Primary Items"
            name: "primary"
            widget: "list"
            summary: "{{fields.link.title}}"
            fields:
              - {
                  label: Link,
                  name: link,
                  widget: link,
                  required: false,
                  collections:
                    [
                      {
                        name: "template_pages",
                        searchFields: ["title"],
                        displayField: "title",
                        valueField: "slug",
                      },
                      {
                        name: "pages",
                        searchFields: ["title"],
                        displayField: "title",
                        valueField: "slug",
                      },
                    ],
                }
          - label: "Secondary Items"
            name: "secondary"
            widget: "list"
            summary: "{{fields.link.title}}"
            fields:
              - {
                  label: Link,
                  name: link,
                  widget: link,
                  required: false,
                  collections:
                    [
                      {
                        name: "template_pages",
                        searchFields: ["title"],
                        displayField: "title",
                        valueField: "slug",
                      },
                      {
                        name: "pages",
                        searchFields: ["title"],
                        displayField: "title",
                        valueField: "slug",
                      },
                    ],
                }
      - file: "src/content/settings/contact.md"
        label: "Contact Details"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact",
            }
          - { label: "Phone number", name: phone, widget: string }
          - { label: "Email", name: email, widget: string }
          - { label: Address, name: address, widget: text }
